alias tf="terraform"
alias g="git"
alias gs="git status"
alias fixup="git commit --fixup"
alias be="bundle exec"
alias l="ls -l"
alias ll="ls -la"
alias dc="docker-compose"
alias run="docker-compose run --rm"
alias k="kubectl"
alias ks="kubesec"
alias rubo="git diff --cached --diff-filter=AM --name-only | sed 's/.*/\"&\"/' | xargs bundle exec rubocop -D --force-exclusion -c .rubocop.yml"
